language: rust
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsnappy-dev
  - curl -sSf https://static.rust-lang.org/rustup.sh > /tmp/rustup.sh && chmod +x /tmp/rustup.sh && sudo /tmp/rustup.sh --channel=nightly --with-target=x86_64-unknown-linux-musl
install: ./make_static.sh
script: ./static.sh